### PR TITLE
using timer1

### PR DESCRIPTION
**Pull request by lopelex**
Using timer1 interrupt.

### CODE REVIEW

**Comment by sh4d0w12** [comment]
Sorry for not getting to it sooner. This looks good but does not seem to work well. Will not merge.

**Comment by anakod** [comment]
@sh4d0w12, @lopelex thanks for great work. Which problem here, can you discover?

**Comment by sh4d0w12** [comment]
I downloaded the pull request and compiled it fine. When I ran my example code with the necessary modifications the performance was very flaky. It would work maybe once or twice. @lopelex solution is far more elegant than mine but didn't seem to work when I tried it. I am sure with some tweaking it would but didn't have time to investigate. When I get a chance to revisit I will see if I can incorporate the changes.

**Comment by anakod** [comment]
@lopelex on which hardware you test it?

**Comment by lopelex** [comment]
@sh4d0w12 now it should work using system_get_cpu_freq() not CPU_CLK_FREQ macro.
@anakod i'm using ESP-ADC from in-circuit.de.

**Comment by anakod** [comment]
> i'm using ESP-ADC from in-circuit.de.

I mean to receive signal from ESP :)

**Comment by lopelex** [comment]
Samsung TV and arduino. Why you want to know? PR is already closed.

**Pull request closed without merging**
